"""Pixel-art cursors in the game's style: off-white fill, dark teal outline, hard drop shadow.

Each cursor is a 16x16 sprite ("#" outline, "s" fill, "d" shade, "r"/"R"/"o" pencil colours); a
shadow is added one pixel down-right, then the sprite is scaled x2 with nearest neighbour (32x32
is the largest size every browser/OS accepts without falling back).

    python scripts/make-cursors.py  ->  public/cursors/*.png
"""

from pathlib import Path

from PIL import Image

OUT = Path(__file__).resolve().parent.parent / "public" / "cursors"
SCALE = 2

FILL = (244, 241, 232, 255)
SHADE = (190, 200, 202, 255)
OUTLINE = (30, 43, 46, 255)
SHADOW = (0, 0, 0, 90)
ACCENT = (254, 95, 85, 255)  # Balatro red
ACCENT_DARK = (190, 60, 52, 255)
WOOD = (253, 162, 0, 255)

CURSORS = {
    # hotspot is in 16x16 sprite pixels
    "arrow": (
        (1, 1),
        """
................
.#..............
.##.............
.#s#............
.#ss#...........
.#sss#..........
.#ssss#.........
.#sssss#........
.#ssssss#.......
.#sssssss#......
.#sss####.......
.#s#.#s#........
.##..#ss#.......
.....#ss#.......
......##........
................
""",
    ),
    "pointer": (
        (6, 1),
        """
................
.....##.........
.....#s#........
.....#s#........
.....#s#........
.....#s###......
.....#sds#d#....
..##.#sdsd#s#...
..#s##ssssssd#..
..#ssssssssss#..
...#sssssssss#..
...#sssssssss#..
....#sssssss#...
.....#ssssss#...
.....########...
................
""",
    ),
    "grab": (
        (8, 8),
        """
................
................
................
......##.##.....
.....#s#s#s##...
.....#s#s#s#s#..
..##.#sdsdsds#..
..#s##ssssssss#.
..#ssssssssssd#.
...#sssssssss#..
...#sssssssss#..
....#sssssss#...
.....#ssssss#...
.....########...
................
................
""",
    ),
    "pen": (
        (1, 14),
        """
................
............##..
...........#rr#.
..........#rrR#.
.........#oooR#.
........#ooo##..
.......#ooo#....
......#ooo#.....
.....#ooo#......
....#ooo#.......
...#ooo#........
..#sso#.........
..#ss#..........
.#dd#...........
.##.............
................
""",
    ),
}


def build(sprite: str) -> Image.Image:
    rows = [r.ljust(16, ".") for r in sprite.strip("\n").split("\n")]
    h, w = len(rows), 16
    img = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    px = img.load()
    colors = {"#": OUTLINE, "s": FILL, "d": SHADE, "r": ACCENT, "R": ACCENT_DARK, "o": WOOD}
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch in colors:
                px[x, y] = colors[ch]
    # hard shadow one sprite pixel down-right, under everything opaque
    out = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    opx = out.load()
    for y in range(h):
        for x in range(w):
            if px[x, y][3] and x + 1 < w and y + 1 < h:
                opx[x + 1, y + 1] = SHADOW
    out.alpha_composite(img)
    return out.resize((w * SCALE, h * SCALE), Image.NEAREST)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for name, (hot, sprite) in CURSORS.items():
        build(sprite).save(OUT / f"{name}.png")
        print(f"{name}.png hotspot {hot[0] * SCALE} {hot[1] * SCALE}")


if __name__ == "__main__":
    main()
